### ISSUE TITLE
Flickr30k dataset

### ISSUE THREAD

**Issue by dido1998** [wllmzhu/G-VUE#7]
Can you tell me the instructions to download the flickr30k dataset used in this repository?

**Comment by huangjy-pku** [comment]
Sorry for the imcomplete guidance and my late reply. You can fill in the form and access Flickr30k dataset at [http://shannon.cs.illinois.edu/DenotationGraph/](http://shannon.cs.illinois.edu/DenotationGraph/). We will complete the guidance soon :)
