### ISSUE TITLE
License terms for the datasets

### ISSUE THREAD

**Issue by kartheekmedathati** [wllmzhu/G-VUE#8]
Hi, 

Thanks for sharing this repository. Are there any plans to consider a subset of permissive datasets with licenses such as MIT, CC0 etc.?

Best,
Kartheek

**Comment by huangjy-pku** [comment]
Hello, the licenses of datasets are listed in Appendix F of [our paper](https://arxiv.org/pdf/2211.15402.pdf). We mainly considered the popularity of datasets and currently there is no plan to involve more permissive datasets :)
